final Map<String, Map<String, String>> labels = {
  'en': {
    'personalExperiencesTitle': 'PERSONAL EXPERIENCES',
    'personalExperiencesDesc': 'I was born in 1991 in Catanzaro (Italy), and I have been working in digital industry since 2014, starting from University.\nI’m a qualified ICT Engineer with Engineering Master’s Degree. I have relevant experience as technical leader and developer, working as frontend, backend and mobile developer, using cloud solutions. My functional roles are coordination among company management, customers management and development team to target the customers needs. I love coding and working with high skilled teams.\n\nMy hobbies are coding, playing bass guitar and electric guitar in a band, doing some sports like running, mountain biking, kayaking, and reading books.',
    'skillsTitle': 'SKILLS',
    'skillsDesc': '- Software Development\n- Architecture Design\n- Database Development\n- Technical management\n- Training',
    'relevantExperiencesTitle': 'RELEVANT EXPERIENCES',
    'relevantExperiencesDesc': '- Development of frontend, backend, mobile applications\n- Design and development of relational and non-relational databases (SQL and NoSQL)\n- Performance analysis of application loads, development of caching solutions to improve performance\n- Development of solutions for securing applications (Penetration Testing)\n- Design and development of Cloud infrastructure solutions on AWS\n- Coordination of the development team and training for junior and middle resources of the team\n- Analysis of customer requirements, drafting of technical solutions and cost estimates',
    'professionalExperiencesTitle': 'PROFESSIONAL EXPERIENCES',
    'professionalExperiencesDesc1': 'Lead developer for frontend, backend and mobile projects. Cloud architectures designer',
    'professionalExperiencesDesc2': 'Developer for public administrations and banking platforms',
    'professionalExperiencesDesc3': 'Backend and Frontend developer for e-commerce platforms',
    'trainingTitle': 'TRAINING',
    'certificationsTitle': 'CERTIFICATIONS',
    'study1': 'State exam for qualification of ICT Engineer',
    'study2': 'Master’s Degree in Biomedical Engineering, 106/110',
    'study3': 'Bachelor Degree in Computer and Biomedical Engineering',
  },
  'it': {
    'personalExperiencesTitle': 'ESPERIENZE PERSONALI',
    'personalExperiencesDesc': "Sono nato nel 1991 a Catanzaro (Italia), e lavoro nel settore digitale dal 2014, iniziando dall'Università.\nSono un Ingegnere ICT qualificato con Laurea Magistrale in Ingegneria. Ho esperienza rilevante come leader tecnico e sviluppatore, lavorando come sviluppatore frontend, backend e mobile, utilizzando soluzioni cloud. I miei ruoli funzionali sono il coordinamento tra la direzione aziendale, la gestione dei clienti e il team di sviluppo per soddisfare le esigenze dei clienti. Adoro programmare e lavorare con team altamente qualificati.\n\nI miei hobby sono programmare, suonare il basso e la chitarra elettrica in una band, praticare alcuni sport come corsa, mountain bike, kayak e leggere libri.",
    'skillsTitle': 'COMPETENZE',
    'skillsDesc': '- Sviluppo software\n- Progettazione architettura\n- Sviluppo database\n- Gestione tecnica\n- Formazione',
    'relevantExperiencesTitle': 'ESPERIENZE RILEVANTI',
    'relevantExperiencesDesc': '- Sviluppo di frontend, backend, applicazioni mobili\n- Progettazione e sviluppo di database relazionali e non relazionali (SQL e NoSQL)\n- Analisi delle prestazioni dei carichi applicativi, sviluppo di soluzioni di caching per migliorare le prestazioni\n- Sviluppo di soluzioni per la messa in sicurezza delle applicazioni (Penetration Testing)\n- Progettazione e sviluppo di soluzioni di infrastruttura Cloud su AWS\n- Coordinamento del team di sviluppo e formazione delle risorse junior e middle del team\n- Analisi dei requisiti del cliente, stesura di soluzioni tecniche e stima dei costi',
    'professionalExperiencesTitle': 'ESPERIENZE PROFESSIONALI',
    'professionalExperiencesDesc1': 'Sviluppatore capo per progetti frontend, backend e mobile. Progettista di architetture cloud',
    'professionalExperiencesDesc2': 'Sviluppatore per pubbliche amministrazioni e piattaforme bancarie',
    'professionalExperiencesDesc3': 'Sviluppatore backend e frontend per piattaforme e-commerce',
    'trainingTitle': 'FORMAZIONE',
    'certificationsTitle': 'CERTIFICAZIONI',
    'study1': 'Esame di Stato per la qualifica di Ingegnere ICT',
    'study2': 'Laurea Magistrale in Ingegneria Biomedica, 106/110',
    'study3': 'Laurea triennale in Ingegneria Informatica e Biomedica',
  },
  'es': {
    'personalExperiencesTitle': 'EXPERIENCIAS PERSONALES',
    'personalExperiencesDesc': 'Nací en 1991 en Catanzaro (Italia) y trabajo en la industria digital desde 2014, desde la universidad.\nSoy ingeniero TIC titulado con máster en ingeniería. Tengo experiencia relevante como líder técnico y desarrollador, trabajando como desarrollador frontend, backend y móvil, utilizando soluciones en Cloud. Mis funciones funcionales son la coordinación entre la dirección de la empresa, la gestión de clientes y el equipo de desarrollo para abordar las necesidades de los clientes. Me encanta codificar y trabajar con equipos altamente calificados.\n\nMis pasatiempos son codificar, tocar el bajo y la guitarra eléctrica en una banda, practicar algunos deportes como correr, andar en bicicleta de montaña, hacer kayak y leer libros.',
    'skillsTitle': 'HABILIDADES',
    'skillsDesc': '- Desarrollo de software\n- Diseño de arquitectura\n- Desarrollo de bases de datos\n- Gestión técnica\n- Capacitación',
    'relevantExperiencesTitle': 'EXPERIENCIAS RELEVANTES',
    'relevantExperiencesDesc': '- Desarrollo de aplicaciones frontend, backend, móviles\n- Diseño y desarrollo de bases de datos relacionales y no relacionales (SQL y NoSQL)\n- Análisis de rendimiento de cargas de aplicaciones, desarrollo de soluciones de caché para mejorar el rendimiento\n- Desarrollo de soluciones para asegurar aplicaciones (Penetration Testing)\n- Diseño y desarrollo de soluciones de infraestructura Cloud en AWS\n- Coordinación del equipo de desarrollo y capacitación de los recursos junior y medios del equipo\n- Análisis de los requisitos del cliente, redacción de soluciones técnicas y coste estimado',
    'professionalExperiencesTitle': 'EXPERIENCIAS PROFESIONALES',
    'professionalExperiencesDesc1': 'Desarrollador líder de proyectos frontend, backend y mobile. Diseñador de arquitecturas en Cloud.',
    'professionalExperiencesDesc2': 'Desarrollador para administraciones públicas y plataformas bancarias',
    'professionalExperiencesDesc3': 'Desarrollador Backend y Frontend para plataformas de comercio electrónico',
    'trainingTitle': 'CAPACITACIÓN',
    'certificationsTitle': 'CERTIFICACIONES',
    'study1': 'Examen estatal para el título de Ingeniero TIC',
    'study2': 'Máster Universitario en Ingeniería Biomédica, 106/110',
    'study3': 'Licenciatura en Ingeniería Informática y Biomédica',
  },
  // Aggiungi altre lingue qui
};
